# Generated by Django 6.0.7 on 2026-08-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfs', '0002_remove_dlc_category_remove_game_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='dlc',
            options={'verbose_name': 'Дополнение (DLC)', 'verbose_name_plural': 'Дополнения (DLC)'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.RemoveField(
            model_name='dlc',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dlc',
            name='video',
        ),
        migrations.RemoveField(
            model_name='game',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='video',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0, unique=True, verbose_name='URL-слаг'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dlc',
            name='is_game_of_the_week',
            field=models.BooleanField(default=False, verbose_name='Игра/Товар недели'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_game_of_the_week',
            field=models.BooleanField(default=False, verbose_name='Игра/Товар недели'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='dlc',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_products', to='mfs.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='dlc',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='dlc',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dlc',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка (%)'),
        ),
        migrations.AlterField(
            model_name='dlc',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='dlc',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='dlc',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_products', to='mfs.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='game',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка (%)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
