# Generated by Django 6.0.7 on 2026-08-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfs', '0003_alter_category_options_alter_dlc_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название подборки')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-слаг')),
            ],
            options={
                'verbose_name': 'Подборка',
                'verbose_name_plural': 'Подборки',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название жанра')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-слаг')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.RemoveField(
            model_name='dlc',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='game',
            name='categories',
        ),
        migrations.AlterField(
            model_name='dlc',
            name='is_game_of_the_week',
            field=models.BooleanField(default=False, verbose_name='Игра недели'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_game_of_the_week',
            field=models.BooleanField(default=False, verbose_name='Игра недели'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_products', to='mfs.collection', verbose_name='Подборки'),
        ),
        migrations.AddField(
            model_name='game',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_products', to='mfs.collection', verbose_name='Подборки'),
        ),
        migrations.AddField(
            model_name='dlc',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_products', to='mfs.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_products', to='mfs.genre', verbose_name='Жанры'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
