# Generated by Django 6.0.7 on 2026-08-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfs', '0004_collection_genre_remove_dlc_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dlc',
            options={'verbose_name': 'DLC', 'verbose_name_plural': 'DLC'},
        ),
        migrations.RemoveField(
            model_name='dlc',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='dlc',
            name='game',
        ),
        migrations.RemoveField(
            model_name='dlc',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='dlc',
            name='is_game_of_the_week',
        ),
        migrations.AddField(
            model_name='game',
            name='is_not_on_steam',
            field=models.BooleanField(default=False, verbose_name='Нет в Steam'),
        ),
        migrations.AlterField(
            model_name='game',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='game_products', to='mfs.collection', verbose_name='Подборки'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='games', to='mfs.genre', verbose_name='Жанры'),
        ),
    ]
