# Generated by Django 6.0.7 on 2026-08-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfs', '0005_alter_dlc_options_remove_dlc_collections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlc',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Детальное описание'),
        ),
        migrations.AddField(
            model_name='game',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='Детальное описание'),
        ),
    ]
