# Generated by Django 6.0.7 on 2026-08-25 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfs', '0006_dlc_long_description_game_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlc',
            name='trailer_file',
            field=models.FileField(blank=True, null=True, upload_to='trailers/', verbose_name='Файл трейлера'),
        ),
        migrations.AddField(
            model_name='game',
            name='trailer_file',
            field=models.FileField(blank=True, null=True, upload_to='trailers/', verbose_name='Файл трейлера'),
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='mfs.game')),
            ],
        ),
    ]
