# Generated by Django 6.0.7 on 2026-08-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfs', '0007_dlc_trailer_file_game_trailer_file_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.ImageField(max_length=250, upload_to='screenshots/'),
        ),
    ]
