# Generated by Django 6.0.7 on 2026-08-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfs', '0009_game_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlc',
            name='cover_hd',
            field=models.ImageField(blank=True, null=True, upload_to='covers_hd/', verbose_name='HD Обложка'),
        ),
        migrations.AddField(
            model_name='game',
            name='cover_hd',
            field=models.ImageField(blank=True, null=True, upload_to='covers_hd/', verbose_name='HD Обложка'),
        ),
    ]
