# Generated by Django 6.0.7 on 2026-08-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfs', '0010_dlc_cover_hd_game_cover_hd'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlc',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='Иконка'),
        ),
    ]
