# Generated by Django 6.0.7 on 2026-08-27 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfs', '0011_dlc_icon_game_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlc',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выхода'),
        ),
    ]
