# Generated by Django 6.0.7 on 2026-09-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfs', '0014_alter_news_options_remove_news_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('update', 'Обновление GameStore'), ('announcement', 'Анонс'), ('tech', 'Технические работы')], default='update', max_length=50, verbose_name='Тип публикации'),
        ),
    ]
