# Generated by Django 6.0.7 on 2026-09-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfs', '0016_alter_news_category_userlibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='playtime_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Сыграно часов'),
        ),
    ]
