# Generated by Django 6.0.7 on 2026-09-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfs', '0017_userlibrary_playtime_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_color',
            field=models.CharField(default='#2a2a2a', max_length=7),
        ),
    ]
