# Generated by Django 6.0.7 on 2026-10-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfs', '0018_profile_avatar_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='О себе'),
        ),
    ]
