# Generated by Django 6.0.7 on 2026-10-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfs', '0019_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accent_color',
            field=models.CharField(default='#6865f2', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='disable_blur',
            field=models.BooleanField(default=False),
        ),
    ]
