# Generated by Django 6.0.7 on 2026-10-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfs', '0020_profile_accent_color_profile_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_stats',
            field=models.BooleanField(default=False),
        ),
    ]
